branches:
  only:
  - master
  - dev
  - issue-3
import:
- source: .travis/test.yml
  if: branch = dev || branch = master || branch = issue-3
  
deploy:
  file_glob: true
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: drop
  on:
    tags: true
    branch: master
