language: python
puthon: 3.8
script: 
  - cd PythonApplication1
  - pytest
  - cd ..
    
deploy:
  provider: releases
  pre-release: true
  api_key:
    secure: 3648aa7eee21b17dcb52d176fcf13c7f2cb9d4d1
  file: 
    - drop.txt
  skip_cleanup: true
  on:
    repo: PolyRibina/TRPO_LR6_Python
    tags: true
