language: python
puthon: 3.8
script: 
  - cd PythonApplication1
  - pytest
  - cd ..
deploy:
  provider: releases
  api_key: acb0dcb898ca45f598dcc03717fb31cd3b110574
  file: 
    - TRPO_LR6_Python
    - TRPO_LR6_Python.sha1
  skip_cleanup: true
  on:
    repo: PolyRibina/TRPO_LR6_Python
    branch: dev
    tags: true
    
