language: python
puthon: 3.8
script: 
  - cd PythonApplication1
  - pytest
  - cd ..
deploy:
  provider: releases
  api_key:
    secure: lMsi8Tpg+h5jp/2AAI0NS9m8JC1p7i5HG8FVa9WC/YBgtkZB3mL9Y/xj/vac7mgSaRwWdYBhks4T/6oiMnJClclVun+ZupDFj0/5T1B9nEikYE4qnBtQB6IllRcN2KoCKEtbhcECPJ8dNu1pNDIDd8h+XHZ/Nu3ZhtKsPEIgRbv9D5jZ8iW7f6uboDuafPUBaggs8iMvxGm2G0vrJlAOHpBwEMTs+9cdWdlOEt6zLISExZMhDaqzd+WV79d0iEJHQKf2dq50R7F18WwhZAV7KV6w/QAiOkPHjJVqHJN0uoftUsnb5OP0eLeS7MNBzRXiMfQYnF4+iFYXPUtDWdbwjGQNVhprgO+UVMVoJCB8Tad98aP7++rG7rr/Z0TtCIFPHSdPPnOQuYkufUAzlHBUU6vQlFtycI8qCEJmPdwID/9uB/a9n/PsxXJomdWGwqfw2KbAwUMG+CdHqCM+J6xwGlAylVdjObJFfK2kTBB6WaOnmSf3X5APsTM5RQyoJTAL8nYIk8+SzeDN8FuiLt1fvNRt+ylUUGQ0LKR/MNpKPMXT9DJY0l77xUw6vPyJnGC7eKp66vbyZ/Vh2chZzT8FTmcPl1LtfOvO9LwNLC3Mx7axgJb3uLUkZUNAO723RWN4hsho6Dxkv9MVlPKAGRkROlL8fA8xCA4y2vy3OP4LvC4=
  file: 
    - TRPO_LR6_Python
    - TRPO_LR6_Python.sha1
  skip_cleanup: true
  on:
    repo: PolyRibina/TRPO_LR6_Python
    branch: dev
    tags: true
    
