language: python
puthon: 3.8
script: 
  - cd PythonApplication1
  - pytest
  - cd ..
deploy:
  provider: releases
  api_key: b18828dd2952f87fcff9e356ead467eaf9fe5043
  file: 
    - TRPO_LR6_Python
    - TRPO_LR6_Python.sha1
  skip_cleanup: true
  on:
    repo: PolyRibina/TRPO_LR6_Python
    branch: dev
    tags: true
    
