branches:
  only:
  - master
  - dev
  - issue-3
import:
- source: .travis/test.yml
  if: branch = dev || branch = master || branch = issue-3
  
  
before_deploy:
- git config --local user.name PolyRibina
- git config --local user.email poly.ribina@gmail.com
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG  

deploy:
  provider: releases
  pre-release: true
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: drop
  on:
    tags: true
